const Joi = require("joi");
const { contractItemSchema } = require("./contractvalidation");

const invoiceSchema = Joi.object({
    proformaid: Joi.number().integer().required(),
    invoiceNo: Joi.string().trim().required(),
    invoiceDate: Joi.date().required(),
    customerId: Joi.number().integer().required(),
    contractId: Joi.number().integer().allow(null),
    consigneeId: Joi.number().integer().required(),
    notifyPartyId: Joi.number().integer().required(),
    contactPersonId: Joi.number().integer().required(),
    termsOfPaymentId: Joi.number().integer().required(),
    invoicepaymentterm: Joi.string().valid("CIF", "CFR", "CPT").required(),
    currency: Joi.string().valid("USD", "INR", "EUR").required(),
    preCarriageBy: Joi.string().valid("Sea", "Air", "Road").required(),
    operatingAirlines: Joi.string().required(),
    flightNo: Joi.string().allow(""),
    countryOfOrigin: Joi.string().required(),
    countryOfFinalDestination: Joi.string().required(),
    portOfLoading: Joi.string().required(),
    portOfFinalDestination: Joi.string().required(),
    packing: Joi.string().required(),
    lcnumber: Joi.string().required(),
    lcDate: Joi.date().required(),
    otherRef: Joi.string().allow("", null),
    description: Joi.string().allow("", null),
    shipingMark: Joi.string().allow(""),
    sizeScale: Joi.string().allow(""),
    cartonweight: Joi.number().allow(""),
    totalAmount: Joi.number().allow("", null),
    items: Joi.array().items(contractItemSchema).min(1).required(),
});


const updateInvoiceSchema = Joi.object({
    // consigneeId: Joi.number().integer().optional(),
    // notifyPartyId: Joi.number().integer().optional(),
    // contactPersonId: Joi.number().integer().optional(),
    // termsOfPaymentId: Joi.number().integer().optional(),
    // preCarriageBy: Joi.string().valid("Sea", "Air", "Road").optional(),
    // operatingAirlines: Joi.string().trim(),
    // countryOfOrigin: Joi.string().trim(),
    // countryOfDestination: Joi.string().trim(),


    sizeScale: Joi.string().trim(),
    packing: Joi.string().trim(),
    portOfLoading: Joi.string().trim(),
    portOfFinalDestination: Joi.string().trim(),
    otherRefrence: Joi.string().trim(),
    cartonWeight: Joi.number(),
    currency: Joi.string().valid("USD", "INR", "EUR"),
    totalAmount: Joi.number(),
    shippingBillNo: Joi.string().trim(),
    shippingDate: Joi.date(),
    awbNo: Joi.string().trim(),
    awbNoDate: Joi.date(),
    grossWeight: Joi.number(),
    narration: Joi.string().trim(),
    cha: Joi.string().trim(),
    stockOutFromPKSGodown: Joi.boolean(),
    stockOutDateTime: Joi.date(),
    factoryCode: Joi.string().trim(),
    lorryNo: Joi.string().trim(),
    shipmentTakenBy: Joi.string().trim(),
    shipmentHandedOverTo: Joi.string().trim(),
    lorryInCustomWarehouse: Joi.boolean(),
    lorryInCustomWarehouseDateTime: Joi.date(),
    lorryOutFromCustomWarehouse: Joi.boolean(),
    lorryOutFromCustomWarehouseDateTime: Joi.date(),
    passedShipmentFromCustom: Joi.boolean(),
    passedShipmentFromCustomDate: Joi.date(),
    containerNo: Joi.string().trim(),
    containerStuffing: Joi.boolean(),
    containerStuffingDate: Joi.date(),
    containerSealNo: Joi.string().trim(),
    flightNo: Joi.string().trim(),
    trainNo: Joi.string().trim(),
    railOut: Joi.boolean(),
    railOutDateTime: Joi.date(),
    dispatchDate: Joi.date(),
    transporterName: Joi.string().trim(),
    vehicleNo: Joi.string().trim(),
    driverName: Joi.string().trim(),
    driverPhone: Joi.string().trim(),
    ewayBillNo: Joi.string().trim(),
    lrNo: Joi.string().trim(),
    delivered: Joi.boolean(),
    deliveredDate: Joi.date(),
    deliveryNarration: Joi.string().trim(),

    customSale: Joi.object({
        customExchangeRate: Joi.number(),
        cifCfrValue: Joi.number(),
        lessFreight: Joi.number(),
        lessInsurance: Joi.number(),
        lessCommission: Joi.number(),
        customFobValue: Joi.number(),
        drawBackPercentage: Joi.number(),
        drawBackValue: Joi.number(),
        drawBackDateReceived: Joi.date(),
        drawBackNarration: Joi.string().trim(),
        focusPercentage: Joi.number(),
        focusValue: Joi.number(),
        focusDateReceived: Joi.date(),
    }).optional(),

    bankSale: Joi.object({
        bankExchangeRate: Joi.number(),
        bankRefNo: Joi.string().trim(),
        bankRefDate: Joi.date(),
        negotiationAmount: Joi.number(),
        lessFreight: Joi.number(),
        lessInsurance: Joi.number(),
        lessCommissionIfAny: Joi.number(),
        bankFobValue: Joi.number(),
        dateOfRealisation: Joi.date(),
        realisationNarration: Joi.string().trim(),
        realisationdueDate: Joi.date(),
        courierCompany: Joi.string().trim(),
        trackingNo: Joi.string().trim(),
    }).optional(),

    items: Joi.array().items(contractItemSchema).optional(),

}).min(1);


module.exports = { invoiceSchema, updateInvoiceSchema }